window:
  title: Vacuum Cleaner Simulation
  width: 2400
  height: 2400
  margin: 100
  fps: 60
  background_color: [0, 0, 0]

map:
  colors:
    wall: [255, 255, 255]
    clean_floor: [205, 170, 125]
    stain: [139, 69, 19]
    vacuum_cleaner: [0, 0, 0]
    grid_lines: [0, 0, 0]
  dimensions:
    columns: 50
    rows: 50
  object_properties:
    stain_size: 1
    number_of_stains: 259

game:
  max_steps: 5000
